services:
  web:
    build: .
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000 --workers=3
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - sample.env
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: attendify
      POSTGRES_USER: attendify
      POSTGRES_PASSWORD: attendify
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
