# Generated by Django 5.2.1 on 2025-05-21 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_rename_classroom_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='class_assigned',
        ),
        migrations.CreateModel(
            name='AttendanceSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='attendance.camera')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='attendance.course')),
            ],
        ),
    ]
