# Generated by Django 5.2.1 on 2025-05-21 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_camera_class_assigned_attendanceschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camera',
            old_name='ip_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='camera',
            old_name='location',
            new_name='name',
        ),
    ]
